### ISSUE TITLE
Training without Gurobi optimizer

### ISSUE THREAD

**Issue by mjay2016** [computational-imaging/ACORN#4]
Hi,

Is it possible to train/test without the Gurobi optimizer?

Regards,
MJay

**Comment by davelindell** [comment]
The code currently only supports the Gurobi optimizer (which is free with an academic license). Gurobi is required to solve the integer linear program (ILP) that optimizes the block decomposition during training. It should be possible to use different software/solver to solve the ILP, but this isn't something we're planning to add to the codebase for now.
